version: '3.5'
services:
  proxy:
    image: traefik:v2.5
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command:
      - '--log.level=DEBUG'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.file.directory=/etc/traefik/dynamic'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.web.address=:80'
      - '--providers.docker.network=pdce2e_back'
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
      - '--entrypoints.web.http.redirections.entryPoint.permanent=true'
    volumes:
      - ${PWD}/docker/traefik/config.yml:/etc/traefik/dynamic/config.yml
      - ${PWD}/docker/traefik/certs:/etc/certs
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      back:
        aliases:
          - api.covoiturage.test
          - s3.covoiturage.test
          - download.covoiturage.test
          - local-pdc-export.s3.covoiturage.test

  mailer:
    image: mailhog/mailhog:v1.0.1
    environment:
      MH_CORS_ORIGIN: '*'
    ports:
      - 1025:1025
    networks:
      - back
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.mailer.rule=Host(`mailer.covoiturage.test`)'
      - 'traefik.http.routers.mailer.entrypoints=websecure'
      - 'traefik.http.routers.mailer.tls=true'
      - 'traefik.http.services.mailer.loadbalancer.server.port=8025'

  postgres:
    build: ./docker/postgres
    ports:
      - 5432:5432
    networks:
      - back
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'test'

  redis:
    build: './docker/redis'
    ports:
      - "6379:6379"
    networks:
      - back

  s3:
    image: minio/minio:edge
    networks:
      - back
    command: 'server /data'
    ports:
      - "9000:9000"
    environment:
      MINIO_DOMAIN: s3.covoiturage.test
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.s3.rule=Host(`s3.covoiturage.test`, `local-pdc-export.s3.covoiturage.test`, `download.covoiturage.test`)'
      - 'traefik.http.routers.s3.entrypoints=websecure'
      - 'traefik.http.routers.s3.tls=true'
      - 'traefik.http.services.s3.loadbalancer.server.port=9000'

  s3-init:
    image: minio/mc:edge
    networks:
      - back
    environment:
      MINIO_URL: http://s3:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_REGION_NAME: fr-par
    entrypoint:
      ['sh', '-c', 'mc alias set minio $$MINIO_URL $$MINIO_ACCESS_KEY $$MINIO_SECRET_KEY && mc mb minio/$$BUCKET']
    depends_on:
      - s3
      - redis

networks:
  back:
