roles:
  - slug: admin
    name: Admin
    permissions:
      - user.list
      - user.invite
      - user.create
      - user.read
      - user.update
      - user.delete
      - aom.list
      - aom.dropdown
      - aom.read
      - operator.users.add
      - operator.users.remove
      - operator.users.list
      - operator.authorisations.add
      - operator.authorisations.remove
      - operator.authorisations.list
      - operator.app.create
      - operator.app.delete
      - operator.app.list
      - operator.list
      - operator.dropdown
      - operator.read
      - operator.create
      - operator.update
      - journey.read
      - journey.create
      - journey.list
      - journey.import
      - profile.read
      - profile.update
      - profile.password
      - profile.delete
  - slug: user
    name: User
    permissions:
      - journey.read
      - journey.list
      - user.list
      - profile.read
      - profile.update
      - profile.password
      - profile.delete
      - aom.dropdown
      - operator.dropdown
