name: Build and Deploy
on:
  push:
    branches:
      - 'feat/prod-autodeploy'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build ğŸ”§
        run: |
          cd dashboard
          yarn
          yarn build:production

      - name: Install SSH Client ğŸ”‘
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.FRONT_DEPLOY_KEY }}

      - name: Deploy ğŸš€
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.FRONT_HOST }}
          username: ${{ secrets.FRONT_USERNAME }}
          key: ${{ secrets.FRONT_DEPLOY_KEY }}
          source: dashboard/dist/dashboard/*
          target: www/${{ env.GITHUB_REF }}
          rm: false
